export const roadmapData = [
  
  {
    topic: "Campus to Corporate",
    name: "Mr. Prasad Narayan",
    designation: "Vice President",
    company: "Leapfrog",
    date: "10th September 2025",
    image: "/inductionimages/10th1new.webp",
    companyLogo: "/inductionlogos/1.webp",
  },
  // {
  //   topic: "Meet Your Mentors",
  //   name: "Mr. Prasad Narayan",
  //   designation: "Vice President",
  //   company: "Leapfrog",
  //   date: "10th September 2025",
  //   image: "/IGSB/student-induction/induction25-1.png",
  //   companyLogo: "/placementlogos/1.webp",
  // },
  {
    topic: "Sahaj Yoga Meditation",
    name: "Mr. Dhanesh Paradkar",
    designation: "Vice President",
    company: "Vodafone UK",
    date: "10th September 2025",
  image: "/inductionimages/10th2new.webp",
    companyLogo: "/inductionlogos/2.webp",
  },
  
  {
    topic: "India 10 on 10",
    name: "Mr. Nishant Modi",
    designation: "Vice President",
    company: "Edelweiss",
    date: "11th September 2025",
    image: "/inductionimages/11th.webp",
    companyLogo: "/inductionlogos/3.webp",
  },
  {
    topic: "Decoding Happiness",
    name: "Ms. Smita Shetty",
    designation: "Managing Trustee",
    company: "Navkshitij Pune",
    date: "11th September 2025",
    image: "/IGSB/student-induction/induction25-2.png",
    companyLogo: "/inductionlogos/4.webp",
  },
  // {
  //   topic: "Living the Core: Universal Human Values",
  //   name: "Dr. Anuradha Phadnis",
  //   designation: "",
  //   company: "",
  //   date: "11th September 2025",
  //   image: "/IGSB/student-induction/induction25-3.png",
  //   companyLogo: "/placementlogos/3.webp",
  // },

  // ===================== 12 SEPTEMBER =====================
  {
    topic: "Make Friends with AI",
    name: "Ms. Nitya N A",
    designation: "Manager Internal Audit Europe and Asia PAC",
    company: "",
    date: "12th September 2025",
    image: "/inductionimages/12th1new.webp",
    companyLogo: "/inductionlogos/5.webp",
  },
  {
    topic: "Learning Through Drama – Interactive Workshop",
    name: "Mr. Soham Dadarkar",
    designation: "Facilitator and Founder",
    company: "",
    date: "12th September 2025",
    image: "/inductionimages/12th2new.webp",
    companyLogo: "/inductionlogos/6.webp",
  },

  // ===================== 13 SEPTEMBER =====================
  {
    topic: "The Executive Edge",
    name: "Ms. Neha Ratnakar",
    designation: "Executive Presence Consultant & Corporate Trainer",
    company: "",
    date: "13th September 2025",
   image: "/inductionimages/13th1new.webp",
    companyLogo: "/inductionlogos/7.webp",
  },
  {
    topic: "The Pattern of Potential",
    name: "Ms. Ummeaiman Ansari",
    designation: "Co-Founder",
    company: "",
    date: "13th September 2025",
    image: "/inductionimages/13th2new.webp",
    companyLogo: "/inductionlogos/8.webp",
  },

  // ===================== 15 SEPTEMBER =====================
  {
    topic: "The Z Factor",
    name: "Mrs. Trupti Pansare",
    designation: "CHRO & Founder",
    company: "Inteliment Technologies",
    date: "15th September 2025",
   image: "/inductionimages/15th1new.webp",
    companyLogo: "/inductionlogos/9.webp",
  },
  {
    topic: "Pharma Horizons",
    name: "Parikshit Baviskar",
    designation: "Regional Business Manager",
    company: "ERIS Lifesciences",
    date: "15th September 2025",
    image: "/inductionimages/15th2new.webp",
   companyLogo: "/inductionlogos/10.webp",
  },

  // ===================== 16 SEPTEMBER =====================
  {
    topic: "Managing Self is Everything",
    name: "Amey Joshi",
    designation: "",
    company: "",
    date: "16th September 2025",
     image: "/inductionimages/16th1new.webp",
   companyLogo: "/inductionlogos/11.webp",
  },
  {
    topic: "Creating Safe Workplaces – POSH Awareness",
    name: "Adv. Meetali Savalekar",
    designation: "Advocate",
    company: "",
    date: "16th September 2025",
      image: "/inductionimages/16th2new.webp",
  //  companyLogo: "",
  },

  // ===================== 17 SEPTEMBER =====================
  {
    topic: "Career Opportunities in Human Capital",
    name: "Dr. Santosh Bhave",
    designation: "",
    company: "",
    date: "17th September 2025",
     image: "/inductionimages/17th1new.webp",
   companyLogo: "/inductionlogos/12.webp",
  },
  {
    topic: "Good to Great",
    name: "Mrs. Vahida Pathan",
    designation: "",
    company: "",
    date: "17th September 2025",
     image: "/inductionimages/17th2new.webp",
   companyLogo: "/inductionlogos/13.webp",
  },
  {
    topic: "Effective Communication",
    name: "Dr. Shweta Lamba",
    designation: "Counselling Psychologist",
    company: "",
    date: "17th September 2025",
      image: "/inductionimages/17th3new.webp",
  //  companyLogo: ""
  },

  // ===================== 18 SEPTEMBER =====================
  {
    topic: "Corporate Yodha – Unleashing the Qu in You",
    name: "Prof. Chetan Wakalkar",
    designation: "",
    company: "",
    date: "18th September 2025",
      image: "/inductionimages/18th1new.webp",
   companyLogo: "/inductionlogos/14.webp",
  },
  {
    topic: "Campus to Corporate Transformation",
    name: "Mr. Kiran Panchal",
    designation: "",
    company: "",
    date: "18th September 2025",
      image: "/inductionimages/18th2.png",
   companyLogo: "/inductionlogos/15.webp",
  },

  // ===================== 19 SEPTEMBER =====================
  {
    topic: "Unlocking Potential for Future Champions",
    name: "Mr. Dilip Chaudhary",
    designation: "",
    company: "",
    date: "19th September 2025",
     image: "/inductionimages/19th1new.webp",
   companyLogo: "/inductionlogos/16.webp",
  },
  {
    topic: "HR Functions Across Companies",
    name: "Dr. Tasneem Khokar",
    designation: "Expert Trainer",
    company: "",
    date: "19th September 2025",
      image: "/inductionimages/19th2.webp",
  //  companyLogo: "",
  },
  {
    topic: "Sales in the City",
    name: "Mr. Ashish Gandevia",
    designation: "",
    company: "",
    date: "19th September 2025",
      image: "/inductionimages/19th3.png",
   companyLogo: "/inductionlogos/17.webp",
  },
];