export const roadmapData = [
  // ===================== 11 SEPTEMBER =====================
  {
    topic: "India 10 on 10",
    name: "Mr. Nishant Modi",
    designation: "Vice President",
    company: "Edelweiss",
    date: "11th September 2025",
    image: "/IGSB/student-induction/induction25-1.png",
    companyLogo: "/placementlogos/1.jpg",
  },
  {
    topic: "Decoding Happiness",
    name: "Ms. Smita Shetty",
    designation: "Managing Trustee",
    company: "Navkshitij Pune",
    date: "11th September 2025",
    image: "/IGSB/student-induction/induction25-2.png",
    companyLogo: "/placementlogos/2.jpg",
  },
  {
    topic: "Living the Core: Universal Human Values",
    name: "Dr. Anuradha Phadnis",
    designation: "",
    company: "",
    date: "11th September 2025",
    image: "/IGSB/student-induction/induction25-3.png",
    companyLogo: "/placementlogos/3.jpg",
  },

  // ===================== 12 SEPTEMBER =====================
  {
    topic: "Make Friends with AI",
    name: "Ms. Nitya N A",
    designation: "",
    company: "",
    date: "12th September 2025",
    image: "/IGSB/student-induction/induction25-4.png",
    companyLogo: "/placementlogos/4.jpg",
  },
  {
    topic: "Learning Through Drama – Interactive Workshop",
    name: "Mr. Soham Dadarkar",
    designation: "",
    company: "",
    date: "12th September 2025",
    image: "/IGSB/student-induction/induction25-5.png",
    companyLogo: "/placementlogos/5.jpg",
  },

  // ===================== 13 SEPTEMBER =====================
  {
    topic: "The Executive Edge",
    name: "Neha Ratnakar",
    designation: "",
    company: "",
    date: "13th September 2025",
    image: "/IGSB/student-induction/induction25-6.png",
    companyLogo: "/placementlogos/6.jpg",
  },
  {
    topic: "The Pattern of Potential",
    name: "Ummeaiman Ansari",
    designation: "",
    company: "",
    date: "13th September 2025",
    image: "/IGSB/student-induction/induction25-7.png",
    companyLogo: "/placementlogos/7.jpg",
  },

  // ===================== 15 SEPTEMBER =====================
  {
    topic: "The Z Factor",
    name: "Mrs. Trupti Pansare",
    designation: "CHRO & Founder",
    company: "Inteliment Technologies",
    date: "15th September 2025",
    image: "/IGSB/student-induction/induction25-8.png",
    companyLogo: "/placementlogos/8.jpg",
  },
  {
    topic: "Pharma Horizons",
    name: "Parikshit Baviskar",
    designation: "Regional Business Manager",
    company: "ERIS Lifesciences",
    date: "15th September 2025",
    image: "/IGSB/student-induction/induction25-9.png",
    companyLogo: "/placementlogos/9.jpg",
  },

  // ===================== 16 SEPTEMBER =====================
  {
    topic: "Managing Self is Everything",
    name: "Amey Joshi",
    designation: "",
    company: "",
    date: "16th September 2025",
    image: "/IGSB/student-induction/induction25-10.png",
    companyLogo: "/placementlogos/10.jpg",
  },
  {
    topic: "Creating Safe Workplaces – POSH Awareness",
    name: "Adv. Meetali Savalekar",
    designation: "",
    company: "",
    date: "16th September 2025",
    image: "/IGSB/student-induction/induction25-11.png",
    companyLogo: "/placementlogos/11.jpg",
  },

  // ===================== 17 SEPTEMBER =====================
  {
    topic: "Career Opportunities in Human Capital",
    name: "Dr. Santosh Bhave",
    designation: "",
    company: "",
    date: "17th September 2025",
    image: "/IGSB/student-induction/induction25-12.png",
    companyLogo: "/placementlogos/12.jpg",
  },
  {
    topic: "Good to Great",
    name: "Mrs. Vahida Pathan",
    designation: "",
    company: "",
    date: "17th September 2025",
    image: "/IGSB/student-induction/induction25-13.png",
    companyLogo: "/placementlogos/13.jpg",
  },
  {
    topic: "Effective Communication",
    name: "Dr. Shweta Lamba",
    designation: "",
    company: "",
    date: "17th September 2025",
    image: "/IGSB/student-induction/induction25-14.png",
    companyLogo: "/placementlogos/14.jpg",
  },

  // ===================== 18 SEPTEMBER =====================
  {
    topic: "Corporate Yodha – Unleashing the Qu in You",
    name: "Prof. Chetan Wakalkar",
    designation: "",
    company: "",
    date: "18th September 2025",
    image: "/IGSB/student-induction/induction25-15.png",
    companyLogo: "/placementlogos/15.jpg",
  },
  {
    topic: "Campus to Corporate Transformation",
    name: "Mr. Kiran Panchal",
    designation: "",
    company: "",
    date: "18th September 2025",
    image: "/IGSB/student-induction/induction25-16.png",
    companyLogo: "/placementlogos/16.jpg",
  },

  // ===================== 19 SEPTEMBER =====================
  {
    topic: "Unlocking Potential for Future Champions",
    name: "Mr. Dilip Chaudhary",
    designation: "",
    company: "",
    date: "19th September 2025",
    image: "/IGSB/student-induction/induction25-17.png",
    companyLogo: "/placementlogos/17.jpg",
  },
  {
    topic: "HR Functions Across Companies",
    name: "Dr. Tasneem Khokar",
    designation: "",
    company: "",
    date: "19th September 2025",
    image: "/IGSB/student-induction/induction25-18.png",
    companyLogo: "/placementlogos/18.jpg",
  },
  {
    topic: "Sales in the City",
    name: "Mr. Ashish Gandevia",
    designation: "",
    company: "",
    date: "19th September 2025",
    image: "/IGSB/student-induction/induction25-19.png",
    companyLogo: "/placementlogos/19.jpg",
  },
];